# theme: jekyll-theme-hacker
title: Cyclic Immunofluorescence
description: A Simple Approach to Highly Multiplexed Cell and Tissue Imaging
# sass:
#     sass_dir: ./_sass

sass:
    load_paths:
        - _sass
        - node_modules
        
# plugins:
#     - jekyll-redirect-from


# For Cloud9 development env
# host: 0.0.0.0
# port: 8080
baseurl: '/blanktest'


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
